// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zoo.proto

package be.steven.d.dog.sometechnologies.zoo;

public interface HabitatOrBuilder extends
    // @@protoc_insertion_point(interface_extends:steven.Habitat)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string habitatName = 1;</code>
   * @return The habitatName.
   */
  java.lang.String getHabitatName();
  /**
   * <code>string habitatName = 1;</code>
   * @return The bytes for habitatName.
   */
  com.google.protobuf.ByteString
      getHabitatNameBytes();

  /**
   * <code>repeated .steven.Keeper keepers = 2;</code>
   */
  java.util.List<be.steven.d.dog.sometechnologies.zoo.Keeper> 
      getKeepersList();
  /**
   * <code>repeated .steven.Keeper keepers = 2;</code>
   */
  be.steven.d.dog.sometechnologies.zoo.Keeper getKeepers(int index);
  /**
   * <code>repeated .steven.Keeper keepers = 2;</code>
   */
  int getKeepersCount();
  /**
   * <code>repeated .steven.Keeper keepers = 2;</code>
   */
  java.util.List<? extends be.steven.d.dog.sometechnologies.zoo.KeeperOrBuilder> 
      getKeepersOrBuilderList();
  /**
   * <code>repeated .steven.Keeper keepers = 2;</code>
   */
  be.steven.d.dog.sometechnologies.zoo.KeeperOrBuilder getKeepersOrBuilder(
      int index);

  /**
   * <code>int32 numberOfAnimals = 3;</code>
   * @return The numberOfAnimals.
   */
  int getNumberOfAnimals();

  /**
   * <code>string food = 4;</code>
   * @return The food.
   */
  java.lang.String getFood();
  /**
   * <code>string food = 4;</code>
   * @return The bytes for food.
   */
  com.google.protobuf.ByteString
      getFoodBytes();
}
