// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zoo.proto

package be.steven.d.dog.sometechnologies.zoo;

public interface HabitatOrBuilder extends
    // @@protoc_insertion_point(interface_extends:steven.Habitat)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 crew = 2;</code>
   * @return The crew.
   */
  int getCrew();

  /**
   * <code>string cargo = 3;</code>
   * @return The cargo.
   */
  java.lang.String getCargo();
  /**
   * <code>string cargo = 3;</code>
   * @return The bytes for cargo.
   */
  com.google.protobuf.ByteString
      getCargoBytes();
}
