// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zoo.proto

package be.steven.d.dog.sometechnologies.zoo;

public interface KeeperOrBuilder extends
    // @@protoc_insertion_point(interface_extends:steven.Keeper)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.steven.Keeper.Role role = 2;</code>
   * @return The enum numeric value on the wire for role.
   */
  int getRoleValue();
  /**
   * <code>.steven.Keeper.Role role = 2;</code>
   * @return The role.
   */
  be.steven.d.dog.sometechnologies.zoo.Keeper.Role getRole();
}
