// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zoo.proto

package be.steven.d.dog.sometechnologies.prototarget.zoo;

/**
 * Protobuf type {@code steven.Habitat}
 */
public final class Habitat extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:steven.Habitat)
    HabitatOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Habitat.newBuilder() to construct.
  private Habitat(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Habitat() {
    habitatName_ = "";
    keepers_ = java.util.Collections.emptyList();
    food_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Habitat();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Habitat(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            habitatName_ = s;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              keepers_ = new java.util.ArrayList<be.steven.d.dog.sometechnologies.prototarget.zoo.Keeper>();
              mutable_bitField0_ |= 0x00000001;
            }
            keepers_.add(
                input.readMessage(be.steven.d.dog.sometechnologies.prototarget.zoo.Keeper.parser(), extensionRegistry));
            break;
          }
          case 24: {

            numberOfAnimals_ = input.readInt32();
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            food_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        keepers_ = java.util.Collections.unmodifiableList(keepers_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return be.steven.d.dog.sometechnologies.prototarget.zoo.ZooOuterClass.internal_static_steven_Habitat_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return be.steven.d.dog.sometechnologies.prototarget.zoo.ZooOuterClass.internal_static_steven_Habitat_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat.class, be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat.Builder.class);
  }

  public static final int HABITATNAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object habitatName_;
  /**
   * <code>string habitatName = 1;</code>
   * @return The habitatName.
   */
  @java.lang.Override
  public java.lang.String getHabitatName() {
    java.lang.Object ref = habitatName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      habitatName_ = s;
      return s;
    }
  }
  /**
   * <code>string habitatName = 1;</code>
   * @return The bytes for habitatName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getHabitatNameBytes() {
    java.lang.Object ref = habitatName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      habitatName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int KEEPERS_FIELD_NUMBER = 2;
  private java.util.List<be.steven.d.dog.sometechnologies.prototarget.zoo.Keeper> keepers_;
  /**
   * <code>repeated .steven.Keeper keepers = 2;</code>
   */
  @java.lang.Override
  public java.util.List<be.steven.d.dog.sometechnologies.prototarget.zoo.Keeper> getKeepersList() {
    return keepers_;
  }
  /**
   * <code>repeated .steven.Keeper keepers = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends be.steven.d.dog.sometechnologies.prototarget.zoo.KeeperOrBuilder> 
      getKeepersOrBuilderList() {
    return keepers_;
  }
  /**
   * <code>repeated .steven.Keeper keepers = 2;</code>
   */
  @java.lang.Override
  public int getKeepersCount() {
    return keepers_.size();
  }
  /**
   * <code>repeated .steven.Keeper keepers = 2;</code>
   */
  @java.lang.Override
  public be.steven.d.dog.sometechnologies.prototarget.zoo.Keeper getKeepers(int index) {
    return keepers_.get(index);
  }
  /**
   * <code>repeated .steven.Keeper keepers = 2;</code>
   */
  @java.lang.Override
  public be.steven.d.dog.sometechnologies.prototarget.zoo.KeeperOrBuilder getKeepersOrBuilder(
      int index) {
    return keepers_.get(index);
  }

  public static final int NUMBEROFANIMALS_FIELD_NUMBER = 3;
  private int numberOfAnimals_;
  /**
   * <code>int32 numberOfAnimals = 3;</code>
   * @return The numberOfAnimals.
   */
  @java.lang.Override
  public int getNumberOfAnimals() {
    return numberOfAnimals_;
  }

  public static final int FOOD_FIELD_NUMBER = 4;
  private volatile java.lang.Object food_;
  /**
   * <code>string food = 4;</code>
   * @return The food.
   */
  @java.lang.Override
  public java.lang.String getFood() {
    java.lang.Object ref = food_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      food_ = s;
      return s;
    }
  }
  /**
   * <code>string food = 4;</code>
   * @return The bytes for food.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFoodBytes() {
    java.lang.Object ref = food_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      food_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getHabitatNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, habitatName_);
    }
    for (int i = 0; i < keepers_.size(); i++) {
      output.writeMessage(2, keepers_.get(i));
    }
    if (numberOfAnimals_ != 0) {
      output.writeInt32(3, numberOfAnimals_);
    }
    if (!getFoodBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, food_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getHabitatNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, habitatName_);
    }
    for (int i = 0; i < keepers_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, keepers_.get(i));
    }
    if (numberOfAnimals_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, numberOfAnimals_);
    }
    if (!getFoodBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, food_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat)) {
      return super.equals(obj);
    }
    be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat other = (be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat) obj;

    if (!getHabitatName()
        .equals(other.getHabitatName())) return false;
    if (!getKeepersList()
        .equals(other.getKeepersList())) return false;
    if (getNumberOfAnimals()
        != other.getNumberOfAnimals()) return false;
    if (!getFood()
        .equals(other.getFood())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + HABITATNAME_FIELD_NUMBER;
    hash = (53 * hash) + getHabitatName().hashCode();
    if (getKeepersCount() > 0) {
      hash = (37 * hash) + KEEPERS_FIELD_NUMBER;
      hash = (53 * hash) + getKeepersList().hashCode();
    }
    hash = (37 * hash) + NUMBEROFANIMALS_FIELD_NUMBER;
    hash = (53 * hash) + getNumberOfAnimals();
    hash = (37 * hash) + FOOD_FIELD_NUMBER;
    hash = (53 * hash) + getFood().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code steven.Habitat}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:steven.Habitat)
      be.steven.d.dog.sometechnologies.prototarget.zoo.HabitatOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return be.steven.d.dog.sometechnologies.prototarget.zoo.ZooOuterClass.internal_static_steven_Habitat_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return be.steven.d.dog.sometechnologies.prototarget.zoo.ZooOuterClass.internal_static_steven_Habitat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat.class, be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat.Builder.class);
    }

    // Construct using be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getKeepersFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      habitatName_ = "";

      if (keepersBuilder_ == null) {
        keepers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        keepersBuilder_.clear();
      }
      numberOfAnimals_ = 0;

      food_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return be.steven.d.dog.sometechnologies.prototarget.zoo.ZooOuterClass.internal_static_steven_Habitat_descriptor;
    }

    @java.lang.Override
    public be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat getDefaultInstanceForType() {
      return be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat.getDefaultInstance();
    }

    @java.lang.Override
    public be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat build() {
      be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat buildPartial() {
      be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat result = new be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat(this);
      int from_bitField0_ = bitField0_;
      result.habitatName_ = habitatName_;
      if (keepersBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          keepers_ = java.util.Collections.unmodifiableList(keepers_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.keepers_ = keepers_;
      } else {
        result.keepers_ = keepersBuilder_.build();
      }
      result.numberOfAnimals_ = numberOfAnimals_;
      result.food_ = food_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat) {
        return mergeFrom((be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat other) {
      if (other == be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat.getDefaultInstance()) return this;
      if (!other.getHabitatName().isEmpty()) {
        habitatName_ = other.habitatName_;
        onChanged();
      }
      if (keepersBuilder_ == null) {
        if (!other.keepers_.isEmpty()) {
          if (keepers_.isEmpty()) {
            keepers_ = other.keepers_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureKeepersIsMutable();
            keepers_.addAll(other.keepers_);
          }
          onChanged();
        }
      } else {
        if (!other.keepers_.isEmpty()) {
          if (keepersBuilder_.isEmpty()) {
            keepersBuilder_.dispose();
            keepersBuilder_ = null;
            keepers_ = other.keepers_;
            bitField0_ = (bitField0_ & ~0x00000001);
            keepersBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getKeepersFieldBuilder() : null;
          } else {
            keepersBuilder_.addAllMessages(other.keepers_);
          }
        }
      }
      if (other.getNumberOfAnimals() != 0) {
        setNumberOfAnimals(other.getNumberOfAnimals());
      }
      if (!other.getFood().isEmpty()) {
        food_ = other.food_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object habitatName_ = "";
    /**
     * <code>string habitatName = 1;</code>
     * @return The habitatName.
     */
    public java.lang.String getHabitatName() {
      java.lang.Object ref = habitatName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        habitatName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string habitatName = 1;</code>
     * @return The bytes for habitatName.
     */
    public com.google.protobuf.ByteString
        getHabitatNameBytes() {
      java.lang.Object ref = habitatName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        habitatName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string habitatName = 1;</code>
     * @param value The habitatName to set.
     * @return This builder for chaining.
     */
    public Builder setHabitatName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      habitatName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string habitatName = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearHabitatName() {
      
      habitatName_ = getDefaultInstance().getHabitatName();
      onChanged();
      return this;
    }
    /**
     * <code>string habitatName = 1;</code>
     * @param value The bytes for habitatName to set.
     * @return This builder for chaining.
     */
    public Builder setHabitatNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      habitatName_ = value;
      onChanged();
      return this;
    }

    private java.util.List<be.steven.d.dog.sometechnologies.prototarget.zoo.Keeper> keepers_ =
      java.util.Collections.emptyList();
    private void ensureKeepersIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        keepers_ = new java.util.ArrayList<be.steven.d.dog.sometechnologies.prototarget.zoo.Keeper>(keepers_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        be.steven.d.dog.sometechnologies.prototarget.zoo.Keeper, be.steven.d.dog.sometechnologies.prototarget.zoo.Keeper.Builder, be.steven.d.dog.sometechnologies.prototarget.zoo.KeeperOrBuilder> keepersBuilder_;

    /**
     * <code>repeated .steven.Keeper keepers = 2;</code>
     */
    public java.util.List<be.steven.d.dog.sometechnologies.prototarget.zoo.Keeper> getKeepersList() {
      if (keepersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(keepers_);
      } else {
        return keepersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .steven.Keeper keepers = 2;</code>
     */
    public int getKeepersCount() {
      if (keepersBuilder_ == null) {
        return keepers_.size();
      } else {
        return keepersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .steven.Keeper keepers = 2;</code>
     */
    public be.steven.d.dog.sometechnologies.prototarget.zoo.Keeper getKeepers(int index) {
      if (keepersBuilder_ == null) {
        return keepers_.get(index);
      } else {
        return keepersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .steven.Keeper keepers = 2;</code>
     */
    public Builder setKeepers(
        int index, be.steven.d.dog.sometechnologies.prototarget.zoo.Keeper value) {
      if (keepersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureKeepersIsMutable();
        keepers_.set(index, value);
        onChanged();
      } else {
        keepersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .steven.Keeper keepers = 2;</code>
     */
    public Builder setKeepers(
        int index, be.steven.d.dog.sometechnologies.prototarget.zoo.Keeper.Builder builderForValue) {
      if (keepersBuilder_ == null) {
        ensureKeepersIsMutable();
        keepers_.set(index, builderForValue.build());
        onChanged();
      } else {
        keepersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .steven.Keeper keepers = 2;</code>
     */
    public Builder addKeepers(be.steven.d.dog.sometechnologies.prototarget.zoo.Keeper value) {
      if (keepersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureKeepersIsMutable();
        keepers_.add(value);
        onChanged();
      } else {
        keepersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .steven.Keeper keepers = 2;</code>
     */
    public Builder addKeepers(
        int index, be.steven.d.dog.sometechnologies.prototarget.zoo.Keeper value) {
      if (keepersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureKeepersIsMutable();
        keepers_.add(index, value);
        onChanged();
      } else {
        keepersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .steven.Keeper keepers = 2;</code>
     */
    public Builder addKeepers(
        be.steven.d.dog.sometechnologies.prototarget.zoo.Keeper.Builder builderForValue) {
      if (keepersBuilder_ == null) {
        ensureKeepersIsMutable();
        keepers_.add(builderForValue.build());
        onChanged();
      } else {
        keepersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .steven.Keeper keepers = 2;</code>
     */
    public Builder addKeepers(
        int index, be.steven.d.dog.sometechnologies.prototarget.zoo.Keeper.Builder builderForValue) {
      if (keepersBuilder_ == null) {
        ensureKeepersIsMutable();
        keepers_.add(index, builderForValue.build());
        onChanged();
      } else {
        keepersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .steven.Keeper keepers = 2;</code>
     */
    public Builder addAllKeepers(
        java.lang.Iterable<? extends be.steven.d.dog.sometechnologies.prototarget.zoo.Keeper> values) {
      if (keepersBuilder_ == null) {
        ensureKeepersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, keepers_);
        onChanged();
      } else {
        keepersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .steven.Keeper keepers = 2;</code>
     */
    public Builder clearKeepers() {
      if (keepersBuilder_ == null) {
        keepers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        keepersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .steven.Keeper keepers = 2;</code>
     */
    public Builder removeKeepers(int index) {
      if (keepersBuilder_ == null) {
        ensureKeepersIsMutable();
        keepers_.remove(index);
        onChanged();
      } else {
        keepersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .steven.Keeper keepers = 2;</code>
     */
    public be.steven.d.dog.sometechnologies.prototarget.zoo.Keeper.Builder getKeepersBuilder(
        int index) {
      return getKeepersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .steven.Keeper keepers = 2;</code>
     */
    public be.steven.d.dog.sometechnologies.prototarget.zoo.KeeperOrBuilder getKeepersOrBuilder(
        int index) {
      if (keepersBuilder_ == null) {
        return keepers_.get(index);  } else {
        return keepersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .steven.Keeper keepers = 2;</code>
     */
    public java.util.List<? extends be.steven.d.dog.sometechnologies.prototarget.zoo.KeeperOrBuilder> 
         getKeepersOrBuilderList() {
      if (keepersBuilder_ != null) {
        return keepersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(keepers_);
      }
    }
    /**
     * <code>repeated .steven.Keeper keepers = 2;</code>
     */
    public be.steven.d.dog.sometechnologies.prototarget.zoo.Keeper.Builder addKeepersBuilder() {
      return getKeepersFieldBuilder().addBuilder(
          be.steven.d.dog.sometechnologies.prototarget.zoo.Keeper.getDefaultInstance());
    }
    /**
     * <code>repeated .steven.Keeper keepers = 2;</code>
     */
    public be.steven.d.dog.sometechnologies.prototarget.zoo.Keeper.Builder addKeepersBuilder(
        int index) {
      return getKeepersFieldBuilder().addBuilder(
          index, be.steven.d.dog.sometechnologies.prototarget.zoo.Keeper.getDefaultInstance());
    }
    /**
     * <code>repeated .steven.Keeper keepers = 2;</code>
     */
    public java.util.List<be.steven.d.dog.sometechnologies.prototarget.zoo.Keeper.Builder> 
         getKeepersBuilderList() {
      return getKeepersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        be.steven.d.dog.sometechnologies.prototarget.zoo.Keeper, be.steven.d.dog.sometechnologies.prototarget.zoo.Keeper.Builder, be.steven.d.dog.sometechnologies.prototarget.zoo.KeeperOrBuilder> 
        getKeepersFieldBuilder() {
      if (keepersBuilder_ == null) {
        keepersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            be.steven.d.dog.sometechnologies.prototarget.zoo.Keeper, be.steven.d.dog.sometechnologies.prototarget.zoo.Keeper.Builder, be.steven.d.dog.sometechnologies.prototarget.zoo.KeeperOrBuilder>(
                keepers_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        keepers_ = null;
      }
      return keepersBuilder_;
    }

    private int numberOfAnimals_ ;
    /**
     * <code>int32 numberOfAnimals = 3;</code>
     * @return The numberOfAnimals.
     */
    @java.lang.Override
    public int getNumberOfAnimals() {
      return numberOfAnimals_;
    }
    /**
     * <code>int32 numberOfAnimals = 3;</code>
     * @param value The numberOfAnimals to set.
     * @return This builder for chaining.
     */
    public Builder setNumberOfAnimals(int value) {
      
      numberOfAnimals_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 numberOfAnimals = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearNumberOfAnimals() {
      
      numberOfAnimals_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object food_ = "";
    /**
     * <code>string food = 4;</code>
     * @return The food.
     */
    public java.lang.String getFood() {
      java.lang.Object ref = food_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        food_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string food = 4;</code>
     * @return The bytes for food.
     */
    public com.google.protobuf.ByteString
        getFoodBytes() {
      java.lang.Object ref = food_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        food_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string food = 4;</code>
     * @param value The food to set.
     * @return This builder for chaining.
     */
    public Builder setFood(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      food_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string food = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearFood() {
      
      food_ = getDefaultInstance().getFood();
      onChanged();
      return this;
    }
    /**
     * <code>string food = 4;</code>
     * @param value The bytes for food to set.
     * @return This builder for chaining.
     */
    public Builder setFoodBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      food_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:steven.Habitat)
  }

  // @@protoc_insertion_point(class_scope:steven.Habitat)
  private static final be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat();
  }

  public static be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Habitat>
      PARSER = new com.google.protobuf.AbstractParser<Habitat>() {
    @java.lang.Override
    public Habitat parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Habitat(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Habitat> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Habitat> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

