// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zoo.proto

package be.steven.d.dog.sometechnologies.prototarget.zoo;

public interface KeeperOrBuilder extends
    // @@protoc_insertion_point(interface_extends:steven.Keeper)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string keeperName = 1;</code>
   * @return The keeperName.
   */
  java.lang.String getKeeperName();
  /**
   * <code>string keeperName = 1;</code>
   * @return The bytes for keeperName.
   */
  com.google.protobuf.ByteString
      getKeeperNameBytes();

  /**
   * <code>.steven.Keeper.Role keeperRole = 2;</code>
   * @return The enum numeric value on the wire for keeperRole.
   */
  int getKeeperRoleValue();
  /**
   * <code>.steven.Keeper.Role keeperRole = 2;</code>
   * @return The keeperRole.
   */
  be.steven.d.dog.sometechnologies.prototarget.zoo.Keeper.Role getKeeperRole();
}
