// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zoo.proto

package be.steven.d.dog.sometechnologies.prototarget.zoo;

/**
 * Protobuf type {@code steven.Zoo}
 */
public final class Zoo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:steven.Zoo)
    ZooOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Zoo.newBuilder() to construct.
  private Zoo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Zoo() {
    habitats_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Zoo();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Zoo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            be.steven.d.dog.sometechnologies.prototarget.zoo.Keeper.Builder subBuilder = null;
            if (manager_ != null) {
              subBuilder = manager_.toBuilder();
            }
            manager_ = input.readMessage(be.steven.d.dog.sometechnologies.prototarget.zoo.Keeper.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(manager_);
              manager_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              habitats_ = new java.util.ArrayList<be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat>();
              mutable_bitField0_ |= 0x00000001;
            }
            habitats_.add(
                input.readMessage(be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        habitats_ = java.util.Collections.unmodifiableList(habitats_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return be.steven.d.dog.sometechnologies.prototarget.zoo.ZooOuterClass.internal_static_steven_Zoo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return be.steven.d.dog.sometechnologies.prototarget.zoo.ZooOuterClass.internal_static_steven_Zoo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            be.steven.d.dog.sometechnologies.prototarget.zoo.Zoo.class, be.steven.d.dog.sometechnologies.prototarget.zoo.Zoo.Builder.class);
  }

  public static final int MANAGER_FIELD_NUMBER = 1;
  private be.steven.d.dog.sometechnologies.prototarget.zoo.Keeper manager_;
  /**
   * <code>.steven.Keeper manager = 1;</code>
   * @return Whether the manager field is set.
   */
  @java.lang.Override
  public boolean hasManager() {
    return manager_ != null;
  }
  /**
   * <code>.steven.Keeper manager = 1;</code>
   * @return The manager.
   */
  @java.lang.Override
  public be.steven.d.dog.sometechnologies.prototarget.zoo.Keeper getManager() {
    return manager_ == null ? be.steven.d.dog.sometechnologies.prototarget.zoo.Keeper.getDefaultInstance() : manager_;
  }
  /**
   * <code>.steven.Keeper manager = 1;</code>
   */
  @java.lang.Override
  public be.steven.d.dog.sometechnologies.prototarget.zoo.KeeperOrBuilder getManagerOrBuilder() {
    return getManager();
  }

  public static final int HABITATS_FIELD_NUMBER = 2;
  private java.util.List<be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat> habitats_;
  /**
   * <code>repeated .steven.Habitat habitats = 2;</code>
   */
  @java.lang.Override
  public java.util.List<be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat> getHabitatsList() {
    return habitats_;
  }
  /**
   * <code>repeated .steven.Habitat habitats = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends be.steven.d.dog.sometechnologies.prototarget.zoo.HabitatOrBuilder> 
      getHabitatsOrBuilderList() {
    return habitats_;
  }
  /**
   * <code>repeated .steven.Habitat habitats = 2;</code>
   */
  @java.lang.Override
  public int getHabitatsCount() {
    return habitats_.size();
  }
  /**
   * <code>repeated .steven.Habitat habitats = 2;</code>
   */
  @java.lang.Override
  public be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat getHabitats(int index) {
    return habitats_.get(index);
  }
  /**
   * <code>repeated .steven.Habitat habitats = 2;</code>
   */
  @java.lang.Override
  public be.steven.d.dog.sometechnologies.prototarget.zoo.HabitatOrBuilder getHabitatsOrBuilder(
      int index) {
    return habitats_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (manager_ != null) {
      output.writeMessage(1, getManager());
    }
    for (int i = 0; i < habitats_.size(); i++) {
      output.writeMessage(2, habitats_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (manager_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getManager());
    }
    for (int i = 0; i < habitats_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, habitats_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof be.steven.d.dog.sometechnologies.prototarget.zoo.Zoo)) {
      return super.equals(obj);
    }
    be.steven.d.dog.sometechnologies.prototarget.zoo.Zoo other = (be.steven.d.dog.sometechnologies.prototarget.zoo.Zoo) obj;

    if (hasManager() != other.hasManager()) return false;
    if (hasManager()) {
      if (!getManager()
          .equals(other.getManager())) return false;
    }
    if (!getHabitatsList()
        .equals(other.getHabitatsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasManager()) {
      hash = (37 * hash) + MANAGER_FIELD_NUMBER;
      hash = (53 * hash) + getManager().hashCode();
    }
    if (getHabitatsCount() > 0) {
      hash = (37 * hash) + HABITATS_FIELD_NUMBER;
      hash = (53 * hash) + getHabitatsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static be.steven.d.dog.sometechnologies.prototarget.zoo.Zoo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static be.steven.d.dog.sometechnologies.prototarget.zoo.Zoo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static be.steven.d.dog.sometechnologies.prototarget.zoo.Zoo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static be.steven.d.dog.sometechnologies.prototarget.zoo.Zoo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static be.steven.d.dog.sometechnologies.prototarget.zoo.Zoo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static be.steven.d.dog.sometechnologies.prototarget.zoo.Zoo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static be.steven.d.dog.sometechnologies.prototarget.zoo.Zoo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static be.steven.d.dog.sometechnologies.prototarget.zoo.Zoo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static be.steven.d.dog.sometechnologies.prototarget.zoo.Zoo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static be.steven.d.dog.sometechnologies.prototarget.zoo.Zoo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static be.steven.d.dog.sometechnologies.prototarget.zoo.Zoo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static be.steven.d.dog.sometechnologies.prototarget.zoo.Zoo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(be.steven.d.dog.sometechnologies.prototarget.zoo.Zoo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code steven.Zoo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:steven.Zoo)
      be.steven.d.dog.sometechnologies.prototarget.zoo.ZooOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return be.steven.d.dog.sometechnologies.prototarget.zoo.ZooOuterClass.internal_static_steven_Zoo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return be.steven.d.dog.sometechnologies.prototarget.zoo.ZooOuterClass.internal_static_steven_Zoo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              be.steven.d.dog.sometechnologies.prototarget.zoo.Zoo.class, be.steven.d.dog.sometechnologies.prototarget.zoo.Zoo.Builder.class);
    }

    // Construct using be.steven.d.dog.sometechnologies.prototarget.zoo.Zoo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getHabitatsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (managerBuilder_ == null) {
        manager_ = null;
      } else {
        manager_ = null;
        managerBuilder_ = null;
      }
      if (habitatsBuilder_ == null) {
        habitats_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        habitatsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return be.steven.d.dog.sometechnologies.prototarget.zoo.ZooOuterClass.internal_static_steven_Zoo_descriptor;
    }

    @java.lang.Override
    public be.steven.d.dog.sometechnologies.prototarget.zoo.Zoo getDefaultInstanceForType() {
      return be.steven.d.dog.sometechnologies.prototarget.zoo.Zoo.getDefaultInstance();
    }

    @java.lang.Override
    public be.steven.d.dog.sometechnologies.prototarget.zoo.Zoo build() {
      be.steven.d.dog.sometechnologies.prototarget.zoo.Zoo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public be.steven.d.dog.sometechnologies.prototarget.zoo.Zoo buildPartial() {
      be.steven.d.dog.sometechnologies.prototarget.zoo.Zoo result = new be.steven.d.dog.sometechnologies.prototarget.zoo.Zoo(this);
      int from_bitField0_ = bitField0_;
      if (managerBuilder_ == null) {
        result.manager_ = manager_;
      } else {
        result.manager_ = managerBuilder_.build();
      }
      if (habitatsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          habitats_ = java.util.Collections.unmodifiableList(habitats_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.habitats_ = habitats_;
      } else {
        result.habitats_ = habitatsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof be.steven.d.dog.sometechnologies.prototarget.zoo.Zoo) {
        return mergeFrom((be.steven.d.dog.sometechnologies.prototarget.zoo.Zoo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(be.steven.d.dog.sometechnologies.prototarget.zoo.Zoo other) {
      if (other == be.steven.d.dog.sometechnologies.prototarget.zoo.Zoo.getDefaultInstance()) return this;
      if (other.hasManager()) {
        mergeManager(other.getManager());
      }
      if (habitatsBuilder_ == null) {
        if (!other.habitats_.isEmpty()) {
          if (habitats_.isEmpty()) {
            habitats_ = other.habitats_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureHabitatsIsMutable();
            habitats_.addAll(other.habitats_);
          }
          onChanged();
        }
      } else {
        if (!other.habitats_.isEmpty()) {
          if (habitatsBuilder_.isEmpty()) {
            habitatsBuilder_.dispose();
            habitatsBuilder_ = null;
            habitats_ = other.habitats_;
            bitField0_ = (bitField0_ & ~0x00000001);
            habitatsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getHabitatsFieldBuilder() : null;
          } else {
            habitatsBuilder_.addAllMessages(other.habitats_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      be.steven.d.dog.sometechnologies.prototarget.zoo.Zoo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (be.steven.d.dog.sometechnologies.prototarget.zoo.Zoo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private be.steven.d.dog.sometechnologies.prototarget.zoo.Keeper manager_;
    private com.google.protobuf.SingleFieldBuilderV3<
        be.steven.d.dog.sometechnologies.prototarget.zoo.Keeper, be.steven.d.dog.sometechnologies.prototarget.zoo.Keeper.Builder, be.steven.d.dog.sometechnologies.prototarget.zoo.KeeperOrBuilder> managerBuilder_;
    /**
     * <code>.steven.Keeper manager = 1;</code>
     * @return Whether the manager field is set.
     */
    public boolean hasManager() {
      return managerBuilder_ != null || manager_ != null;
    }
    /**
     * <code>.steven.Keeper manager = 1;</code>
     * @return The manager.
     */
    public be.steven.d.dog.sometechnologies.prototarget.zoo.Keeper getManager() {
      if (managerBuilder_ == null) {
        return manager_ == null ? be.steven.d.dog.sometechnologies.prototarget.zoo.Keeper.getDefaultInstance() : manager_;
      } else {
        return managerBuilder_.getMessage();
      }
    }
    /**
     * <code>.steven.Keeper manager = 1;</code>
     */
    public Builder setManager(be.steven.d.dog.sometechnologies.prototarget.zoo.Keeper value) {
      if (managerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        manager_ = value;
        onChanged();
      } else {
        managerBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.steven.Keeper manager = 1;</code>
     */
    public Builder setManager(
        be.steven.d.dog.sometechnologies.prototarget.zoo.Keeper.Builder builderForValue) {
      if (managerBuilder_ == null) {
        manager_ = builderForValue.build();
        onChanged();
      } else {
        managerBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.steven.Keeper manager = 1;</code>
     */
    public Builder mergeManager(be.steven.d.dog.sometechnologies.prototarget.zoo.Keeper value) {
      if (managerBuilder_ == null) {
        if (manager_ != null) {
          manager_ =
            be.steven.d.dog.sometechnologies.prototarget.zoo.Keeper.newBuilder(manager_).mergeFrom(value).buildPartial();
        } else {
          manager_ = value;
        }
        onChanged();
      } else {
        managerBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.steven.Keeper manager = 1;</code>
     */
    public Builder clearManager() {
      if (managerBuilder_ == null) {
        manager_ = null;
        onChanged();
      } else {
        manager_ = null;
        managerBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.steven.Keeper manager = 1;</code>
     */
    public be.steven.d.dog.sometechnologies.prototarget.zoo.Keeper.Builder getManagerBuilder() {
      
      onChanged();
      return getManagerFieldBuilder().getBuilder();
    }
    /**
     * <code>.steven.Keeper manager = 1;</code>
     */
    public be.steven.d.dog.sometechnologies.prototarget.zoo.KeeperOrBuilder getManagerOrBuilder() {
      if (managerBuilder_ != null) {
        return managerBuilder_.getMessageOrBuilder();
      } else {
        return manager_ == null ?
            be.steven.d.dog.sometechnologies.prototarget.zoo.Keeper.getDefaultInstance() : manager_;
      }
    }
    /**
     * <code>.steven.Keeper manager = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        be.steven.d.dog.sometechnologies.prototarget.zoo.Keeper, be.steven.d.dog.sometechnologies.prototarget.zoo.Keeper.Builder, be.steven.d.dog.sometechnologies.prototarget.zoo.KeeperOrBuilder> 
        getManagerFieldBuilder() {
      if (managerBuilder_ == null) {
        managerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            be.steven.d.dog.sometechnologies.prototarget.zoo.Keeper, be.steven.d.dog.sometechnologies.prototarget.zoo.Keeper.Builder, be.steven.d.dog.sometechnologies.prototarget.zoo.KeeperOrBuilder>(
                getManager(),
                getParentForChildren(),
                isClean());
        manager_ = null;
      }
      return managerBuilder_;
    }

    private java.util.List<be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat> habitats_ =
      java.util.Collections.emptyList();
    private void ensureHabitatsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        habitats_ = new java.util.ArrayList<be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat>(habitats_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat, be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat.Builder, be.steven.d.dog.sometechnologies.prototarget.zoo.HabitatOrBuilder> habitatsBuilder_;

    /**
     * <code>repeated .steven.Habitat habitats = 2;</code>
     */
    public java.util.List<be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat> getHabitatsList() {
      if (habitatsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(habitats_);
      } else {
        return habitatsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .steven.Habitat habitats = 2;</code>
     */
    public int getHabitatsCount() {
      if (habitatsBuilder_ == null) {
        return habitats_.size();
      } else {
        return habitatsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .steven.Habitat habitats = 2;</code>
     */
    public be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat getHabitats(int index) {
      if (habitatsBuilder_ == null) {
        return habitats_.get(index);
      } else {
        return habitatsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .steven.Habitat habitats = 2;</code>
     */
    public Builder setHabitats(
        int index, be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat value) {
      if (habitatsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHabitatsIsMutable();
        habitats_.set(index, value);
        onChanged();
      } else {
        habitatsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .steven.Habitat habitats = 2;</code>
     */
    public Builder setHabitats(
        int index, be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat.Builder builderForValue) {
      if (habitatsBuilder_ == null) {
        ensureHabitatsIsMutable();
        habitats_.set(index, builderForValue.build());
        onChanged();
      } else {
        habitatsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .steven.Habitat habitats = 2;</code>
     */
    public Builder addHabitats(be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat value) {
      if (habitatsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHabitatsIsMutable();
        habitats_.add(value);
        onChanged();
      } else {
        habitatsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .steven.Habitat habitats = 2;</code>
     */
    public Builder addHabitats(
        int index, be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat value) {
      if (habitatsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHabitatsIsMutable();
        habitats_.add(index, value);
        onChanged();
      } else {
        habitatsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .steven.Habitat habitats = 2;</code>
     */
    public Builder addHabitats(
        be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat.Builder builderForValue) {
      if (habitatsBuilder_ == null) {
        ensureHabitatsIsMutable();
        habitats_.add(builderForValue.build());
        onChanged();
      } else {
        habitatsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .steven.Habitat habitats = 2;</code>
     */
    public Builder addHabitats(
        int index, be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat.Builder builderForValue) {
      if (habitatsBuilder_ == null) {
        ensureHabitatsIsMutable();
        habitats_.add(index, builderForValue.build());
        onChanged();
      } else {
        habitatsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .steven.Habitat habitats = 2;</code>
     */
    public Builder addAllHabitats(
        java.lang.Iterable<? extends be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat> values) {
      if (habitatsBuilder_ == null) {
        ensureHabitatsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, habitats_);
        onChanged();
      } else {
        habitatsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .steven.Habitat habitats = 2;</code>
     */
    public Builder clearHabitats() {
      if (habitatsBuilder_ == null) {
        habitats_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        habitatsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .steven.Habitat habitats = 2;</code>
     */
    public Builder removeHabitats(int index) {
      if (habitatsBuilder_ == null) {
        ensureHabitatsIsMutable();
        habitats_.remove(index);
        onChanged();
      } else {
        habitatsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .steven.Habitat habitats = 2;</code>
     */
    public be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat.Builder getHabitatsBuilder(
        int index) {
      return getHabitatsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .steven.Habitat habitats = 2;</code>
     */
    public be.steven.d.dog.sometechnologies.prototarget.zoo.HabitatOrBuilder getHabitatsOrBuilder(
        int index) {
      if (habitatsBuilder_ == null) {
        return habitats_.get(index);  } else {
        return habitatsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .steven.Habitat habitats = 2;</code>
     */
    public java.util.List<? extends be.steven.d.dog.sometechnologies.prototarget.zoo.HabitatOrBuilder> 
         getHabitatsOrBuilderList() {
      if (habitatsBuilder_ != null) {
        return habitatsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(habitats_);
      }
    }
    /**
     * <code>repeated .steven.Habitat habitats = 2;</code>
     */
    public be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat.Builder addHabitatsBuilder() {
      return getHabitatsFieldBuilder().addBuilder(
          be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat.getDefaultInstance());
    }
    /**
     * <code>repeated .steven.Habitat habitats = 2;</code>
     */
    public be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat.Builder addHabitatsBuilder(
        int index) {
      return getHabitatsFieldBuilder().addBuilder(
          index, be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat.getDefaultInstance());
    }
    /**
     * <code>repeated .steven.Habitat habitats = 2;</code>
     */
    public java.util.List<be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat.Builder> 
         getHabitatsBuilderList() {
      return getHabitatsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat, be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat.Builder, be.steven.d.dog.sometechnologies.prototarget.zoo.HabitatOrBuilder> 
        getHabitatsFieldBuilder() {
      if (habitatsBuilder_ == null) {
        habitatsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat, be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat.Builder, be.steven.d.dog.sometechnologies.prototarget.zoo.HabitatOrBuilder>(
                habitats_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        habitats_ = null;
      }
      return habitatsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:steven.Zoo)
  }

  // @@protoc_insertion_point(class_scope:steven.Zoo)
  private static final be.steven.d.dog.sometechnologies.prototarget.zoo.Zoo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new be.steven.d.dog.sometechnologies.prototarget.zoo.Zoo();
  }

  public static be.steven.d.dog.sometechnologies.prototarget.zoo.Zoo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Zoo>
      PARSER = new com.google.protobuf.AbstractParser<Zoo>() {
    @java.lang.Override
    public Zoo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Zoo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Zoo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Zoo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public be.steven.d.dog.sometechnologies.prototarget.zoo.Zoo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

