// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zoo.proto

package be.steven.d.dog.sometechnologies.prototarget.zoo;

public interface ZooOrBuilder extends
    // @@protoc_insertion_point(interface_extends:steven.Zoo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.steven.Keeper manager = 1;</code>
   * @return Whether the manager field is set.
   */
  boolean hasManager();
  /**
   * <code>.steven.Keeper manager = 1;</code>
   * @return The manager.
   */
  be.steven.d.dog.sometechnologies.prototarget.zoo.Keeper getManager();
  /**
   * <code>.steven.Keeper manager = 1;</code>
   */
  be.steven.d.dog.sometechnologies.prototarget.zoo.KeeperOrBuilder getManagerOrBuilder();

  /**
   * <code>repeated .steven.Habitat habitats = 2;</code>
   */
  java.util.List<be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat> 
      getHabitatsList();
  /**
   * <code>repeated .steven.Habitat habitats = 2;</code>
   */
  be.steven.d.dog.sometechnologies.prototarget.zoo.Habitat getHabitats(int index);
  /**
   * <code>repeated .steven.Habitat habitats = 2;</code>
   */
  int getHabitatsCount();
  /**
   * <code>repeated .steven.Habitat habitats = 2;</code>
   */
  java.util.List<? extends be.steven.d.dog.sometechnologies.prototarget.zoo.HabitatOrBuilder> 
      getHabitatsOrBuilderList();
  /**
   * <code>repeated .steven.Habitat habitats = 2;</code>
   */
  be.steven.d.dog.sometechnologies.prototarget.zoo.HabitatOrBuilder getHabitatsOrBuilder(
      int index);
}
